<?php

namespace App\Command;

use App\Entity\Category;
use App\Entity\ConditionProduct;
use App\Entity\Product;
use App\Entity\MediaUrl;
use App\Entity\Manufacter;
use App\Entity\ProductVariation;
use App\Repository\ProductRepository;
use App\Services\Factory\ProductFactory;
use App\Services\Normalizer\Product\ProductNormaliserFromPrestaShop;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Serializer\Encoder\CsvEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

#[AsCommand(
    name: 'app:create-product-from-prestashop-Product_csv',
    description: 'load csv from file',
)]
class PrestashopCSVToProduct extends Command
{
    private EntityManagerInterface $entityManager;
    private string $fileDirectory;

    private SymfonyStyle $io;

    private ProductRepository $productRepository;

    public function __construct(
        EntityManagerInterface $entityManager,
        string                 $fileDirectory,
        ProductRepository      $productRepository
    )
    {
        parent::__construct();
        $this->fileDirectory = $fileDirectory;
        $this->entityManager = $entityManager;
        $this->productRepository = $productRepository;
    }

    protected function configure(): void
    {

        $this->setDescription('load csv from file');
//            ->addArgument('arg1', InputArgument::OPTIONAL, 'Argument description')
//            ->addOption('option1', null, InputOption::VALUE_NONE, 'Option description')
        ;
    }

    protected function initialize(InputInterface $input, OutputInterface $output): void
    {
//        parent::initialize($input, $output); // TODO: Change the autogenerated stub
        $this->io = new SymfonyStyle($input, $output);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {

        $this->CreateProduct();

        return Command::SUCCESS;
    }

    private function getDataFromFile(): array
    {
        $file = $this->fileDirectory . 'files-products-csv-prestashop-presta-product-2570-fr.csv';

        $fileExtention = pathinfo($file, PATHINFO_EXTENSION);

        $normalizers = [new ObjectNormalizer()];

        $encoders = [
            new CsvEncoder()
        ];

        $serializer = new Serializer($normalizers, $encoders);

        /** @var  string $fileString */
        $fileString = file_get_contents($file);

        $data = $serializer->decode($fileString, $fileExtention, [CsvEncoder::DELIMITER_KEY => ';']);
        return $data;
    }


    private function CreateProduct()
    {

        $this->io->section('Creation des Product a partir du fichier');

        $productCreated = 0;
        foreach ($this->getDataFromFile() as $row) {
//            "﻿ID" => " ID" IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            if (array_key_exists("﻿ID", $row)) {
                $product = $this->productRepository->findOneBy([
                    'ext_id' => $row["﻿ID"]
                ]);
                if (!$product) {
                    try {

                        //Replace string categories in Row Categories/Entities
                        $arrayStrCategory = explode(",", $row['CATEGORIES']);
                        $arrayCategory = $this->entityManager->getRepository(Category::class)->getArrayIdByArrayCode($arrayStrCategory);
                        $newArrayCategories = [];
                        foreach ($arrayCategory as $category) {
                            $newArrayCategories[] = $category;
                        }
                        $row['CATEGORIES'] = $newArrayCategories;

                        //IS_MAIN for firstProductVariant
                        $row['IS_MAIN'] = true;

                        $newArrayUrls = [];
                        $imgs = explode(",", $row['IMAGES_URL']);

                        $is_main = true;
                        foreach ($imgs as $img) {
                            if ($img != "") {
                                $fileExtention = pathinfo($img, PATHINFO_EXTENSION);

                                $newImage = new MediaUrl();
                                $newImage->setMimeType("image/" . $fileExtention);
                                $newImage->setName("no definition");
                                $newImage->setUrlLink($img);
                                $newImage->setCreatedAt(new \DateTimeImmutable('now'));
                                $newImage->setUpdatedAt(new \DateTimeImmutable('now'));
                                $newImage->setIsMain($is_main);

                                if ($is_main) {
                                    $is_main = false;
                                }
                                $newArrayUrls[] = $newImage;
                                $this->entityManager->persist($newImage);
                            }

                        }
                        $row['IMAGES_URL'] = $newArrayUrls;


                        $manufacter = $this->entityManager->getRepository(Manufacter::class)->findOneBy([
                            'ext_id' => intval($row['MANUFACTER'])
                        ]);
                        if (!$manufacter) {
                            $manufacter = new Manufacter();
                            $manufacter->setExtId(intval($row['MANUFACTER']));
                            $manufacter->setName($this->generateRandomString(10));
                            $this->entityManager->persist($manufacter);
                        }
                        $row['MANUFACTER'] = $manufacter;
                        //Create product/entity from prestashop
                        $product = (new ProductFactory($this->entityManager))->buildProduct(new ProductNormaliserFromPrestaShop($row));
                        $this->entityManager->persist($product);

//                        $productVariation = new ProductVariation();



//                        //Build product
//                        $product->setWidth(floatval($row['WIDTH']));
//                        $product->setExtReference(floatval($row['bb_REFERENCE']));
//                        $product->setName($row['NAME']);
//                        $product->setHeight(floatval($row['HEIGHT']));
//                        $product->setDepth(floatval($row['DEPTH']));
//                        $product->setWeight(floatval($row['WEIGHT']));
//                        $product->setCreatedAt(new \DateTimeImmutable('now'));
//                        $product->setUpdatedAt(new \DateTimeImmutable('now'));
//                        $product->setExtReference($row['bb_REFERENCE']);
//                        $product->setDescription($row['DESCRIPTION']);
//                        $product->setShortDescription($row['SHORT_DESCRIPTION']);
//
//                        $product->setHasVariation(false);
//
//                        // Build product variation
//                        $productVariation->setExtId($row["﻿ID"]);
//                        $productVariation->setName($row['NAME']);
//                        $productVariation->setQuantity($row['QUANTITY']);
//                        $productVariation->setMinimalQuantity($row['MINIMAL_QUANTITY']);
//                        $productVariation->setEan13($row['EAN13']);
//                        $productVariation->setMinimalQuantity($row['MINIMAL_QUANTITY']);
//                        $productVariation->setPriceTaxExclude($row['PRICE_TAX_EXCLUDE']);
//                        $productVariation->setOnSale(false);
//                        $productVariation->setWholesalePrice($row['WHOLESALE_PRICE']);
//                        $productVariation->setCreatedAt(new \DateTimeImmutable('now'));
//                        $productVariation->setUpdatedAt(new \DateTimeImmutable('now'));
//                        $condition = $this->entityManager->getRepository(ConditionProduct::class)->findOneBy(['current_condition' => $row['CONDITION']]);
//                        $productVariation->setConditionProductId($condition);
//                        $productVariation->setExtReference($row['bb_REFERENCE']);
//                        $productVariation->setIsMain(true);









                        $this->entityManager->persist($product);
                        try {
                            $this->entityManager->flush();

                        } catch (\Exception $e) {
                            $this->io->section($e);
                        }
                    } catch (\Exception $e) {
                        $this->io->section($e);
                    }
                }
            }
        }


//        $this->getDataFromFile();
//        if ($categoryCreated != 0) {
//            $string = "{$categoryCreated} Category Créé en Base de Donnée";
//        } else {
//            $string = "Aucune  Category créé en Base de Donnée";
//        }
        $this->io->success('success');
    }

    private function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[random_int(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    private function getMimeType(string $ext)
    {

        switch (strtolower($ext)) {
            case"jpg":
                return "image/jpg";
        }
    }
}
