<?php

namespace App\Command;

use App\Entity\Category;
use App\Entity\ConditionProduct;
use App\Entity\MediaUrl;
use App\Entity\Product;
use App\Entity\Attribute;
use App\Entity\Manufacter;
use App\Entity\ProductVariation;
use App\Repository\ProductRepository;
use App\Repository\CategoryRepository;
use App\Repository\ManufacterRepository;
use App\Repository\ProductVariationRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Serializer\Encoder\CsvEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

#[AsCommand(
    name: 'app:create-product-variation-from-prestashop_csv',
    description: 'load csv from file',
)]
class PrestashopCSVToProductVariation extends Command
{
    private EntityManagerInterface $entityManager;
    private string $fileDirectory;

    private SymfonyStyle $io;

    private ProductVariationRepository $productVariationRepository;

    public function __construct(
        EntityManagerInterface     $entityManager,
        string                     $fileDirectory,
        ProductVariationRepository $productVariationRepository
    )
    {
        parent::__construct();
        $this->fileDirectory = $fileDirectory;
        $this->entityManager = $entityManager;
        $this->productVariationRepository = $productVariationRepository;
    }

    protected function configure(): void
    {

        $this->setDescription('load csv from file');
//            ->addArgument('arg1', InputArgument::OPTIONAL, 'Argument description')
//            ->addOption('option1', null, InputOption::VALUE_NONE, 'Option description')
        ;
    }

    protected function initialize(InputInterface $input, OutputInterface $output): void
    {
//        parent::initialize($input, $output); // TODO: Change the autogenerated stub
        $this->io = new SymfonyStyle($input, $output);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {

        $this->CreateProduct();

        return Command::SUCCESS;
    }

    private function getDataFromFile(): array
    {
        $file = $this->fileDirectory . 'files-combinations-csv-prestashop-presta-combination-2570-fr.csv';

        $fileExtention = pathinfo($file, PATHINFO_EXTENSION);

        $normalizers = [new ObjectNormalizer()];

        $encoders = [
            new CsvEncoder()
        ];

        $serializer = new Serializer($normalizers, $encoders);

        /** @var  string $fileString */
        $fileString = file_get_contents($file);

        $data = $serializer->decode($fileString, $fileExtention, [CsvEncoder::DELIMITER_KEY => ';']);

        return $data;
    }


    private function CreateProduct()
    {

        $this->io->section('Creation des Product a partir du fichier');

        $productCreated = 0;
        foreach ($this->getDataFromFile() as $row) {
//            "﻿PRODUCT_ID" => " PRODUCT_ID" IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            if (array_key_exists("REFERENCE", $row)) {
                $productVariationExist = $this->productVariationRepository->findOneBy([
                    'ext_reference' => $row["REFERENCE"]
                ]);
                if (!$productVariationExist) {
                    try {
                        $productVariation = new ProductVariation();
                        $product = $this->entityManager->getRepository(Product::class)->findOneBy([
                            'ext_id' => intval($row['﻿PRODUCT_ID'])
                        ]);
                        $mainProductVariation = $this->entityManager->getRepository(ProductVariation::class)->findOneBy([
                            'ext_id' => intval($row['﻿PRODUCT_ID']),
                            'is_main' => true
                        ]);
                        if ($product) {

                            $productVariation->setExtId($row["﻿PRODUCT_ID"]);
                            $productVariation->setName($mainProductVariation->getName());
                            $productVariation->setQuantity($row['QUANTITY']);
                            $productVariation->setMinimalQuantity($row['MINIMAL_QUANTITY']);
                            $productVariation->setEan13($row['EAN13']);
                            $productVariation->setMinimalQuantity($row['MINIMAL_QUANTITY']);
                            $productVariation->setPriceTaxExclude($mainProductVariation->getPriceTaxExclude());
                            $productVariation->setOnSale(false);
                            $productVariation->setWholesalePrice($row['WHOLESALE_PRICE']);
                            $productVariation->setCreatedAt(new \DateTimeImmutable('now'));
                            $productVariation->setUpdatedAt(new \DateTimeImmutable('now'));
                            $productVariation->setConditionProductId($mainProductVariation->getConditionProductId());
                            $productVariation->setExtReference($row['REFERENCE']);
                            $productVariation->setIsMain(false);

                            $attribute = new Attribute();
                            $attribute->setName($row['ATTRIBUTE']);
                            $attribute->setValue($row['VALUE']);
                            $attribute->setCreatedAt(new \DateTimeImmutable('now'));
                            $attribute->setUpdatedAt(new \DateTimeImmutable('now'));

                            $imgs = explode(",", $row['IMAGE_URL']);
                            foreach ($imgs as $img) {
                                $fileExtention = pathinfo($img, PATHINFO_EXTENSION);
                                $newImage = new MediaUrl();

                                $newImage->setMimeType("image/".$fileExtention);
                                $newImage->setName("no definition");
                                $newImage->setUrlLink($img);
                                $newImage->setCreatedAt(new \DateTimeImmutable('now'));
                                $newImage->setUpdatedAt(new \DateTimeImmutable('now'));

                                $productVariation->addMediaUrl($newImage);
                                $this->entityManager->persist($newImage);
                            }


                            $productVariation->setAttribute($attribute);

                            $productVariation->setManufacterId($mainProductVariation->getManufacterId());
                            $this->entityManager->persist($productVariation);
                            $product->addProductVariation($productVariation);
                            $product->setHasVariation(true);

                            $this->entityManager->persist($product);



                            try {
                                $this->entityManager->flush();
                            } catch (\Exception $e) {
                                $this->io->section($e);
                            }

                        }

                    } catch (\Exception $e) {
                        $this->io->section($e);
                    }
                }
            }
        }


//        $this->getDataFromFile();
//        if ($categoryCreated != 0) {
//            $string = "{$categoryCreated} Category Créé en Base de Donnée";
//        } else {
//            $string = "Aucune  Category créé en Base de Donnée";
//        }
        $this->io->success('success');
    }

    private function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[random_int(0, $charactersLength - 1)];
        }
        return $randomString;
    }
}
