controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /admin
    controller: App\Controller\DashboardController::index
#------------------------------AUTH------------------------------------

app_login:
  path: /login
  controller: App\Controller\Auth\LoginController::index

app_logout:
  path: /logout
  controller: App\Controller\Auth\LogoutController::logout

#------------------------------user------------------------------------
user_list:
  path: /admin/user-edit
  controller: App\Controller\UserManagementController::index

user_save:
  path: /admin/user-save/{id}
  controller: App\Controller\UserManagementController::saveUser

user_delete:
  path: /admin/user-delete/{id}
  controller: App\Controller\UserManagementController::deleteUser

user_create:
  path: /admin/user-create
  controller: App\Controller\UserManagementController::createUser

#------------------------------product------------------------------------
products_list:
    path: /admin/products
    controller: App\Controller\ProductsController::index

product_edit:
  path: /admin/product-edit/{id}
  controller: App\Controller\ProductsController::editProduct

product_create:
  path: /admin/product-create
  controller: App\Controller\ProductsController::createProduct

product_delete:
  path: /admin/product-delete/{id}
  controller: App\Controller\ProductsController::deleteProduct

#------------------------------product_variation------------------------------------
product_variation_edit:
  path: /admin/product-variation-edit/{id}
  controller: App\Controller\ProductVariationController::editProductVariation

product_variation_create:
  path: /admin/product-variation-create
  controller: App\Controller\ProductVariationController::createProductVariation

product_variation_delete:
  path: /admin/product-variation-delete/{id}
  controller: App\Controller\ProductVariationController::deleteProductVariation
#------------------------------category------------------------------------
categories_list:
     path: /admin/categories
     controller: App\Controller\CategoriesController::index

categories_create:
  path: /admin/category-create
  controller: App\Controller\CategoriesController::createCategory

category_edit:
  path: /admin/category-edit/{id}
  controller: App\Controller\CategoriesController::editCategory

#------------------------------category------------------------------------
discount_list:
  path: /admin/discounts
  controller: App\Controller\DiscountController::index

discount_create:
  path: /admin/discount-create
  controller: App\Controller\DiscountController::createDiscount

discount_save:
  path: /admin/discount-edit/{id}
  controller: App\Controller\DiscountController::saveDiscount

discount_delete:
  path: /admin/discounts-delete/{id}
  controller: App\Controller\DiscountController::deleteDiscount

#------------------------------tax_rule------------------------------------
tax_rule_list:
  path: /admin/tax-rules
  controller: App\Controller\TaxRuleController::index

tax_rule_create:
  path: /admin/tax-rule-create
  controller: App\Controller\TaxRuleController::createTaxRule

tax_rule_save:
  path: /admin/tax-rule-edit/{id}
  controller: App\Controller\TaxRuleController::saveTaxRule

tax_rule_delete:
  path: /admin/tax-rule-delete/{id}
  controller: App\Controller\TaxRuleController::deleteTaxRule

#------------------------------attribute------------------------------------
attribute_list:
  path: /admin/attribute-rules
  controller: App\Controller\AttributeController::index

attribute_create:
  path: /admin/attribute-create
  controller: App\Controller\AttributeController::createAttribute

attribute_save:
  path: /admin/attribute-edit/{id}
  controller: App\Controller\AttributeController::saveAttribute

attribute_delete:
  path: /admin/attribute-delete/{id}
  controller: App\Controller\AttributeController::deleteAttribute

#------------------------------manufacter------------------------------------
manufacter_list:
  path: /admin/manufacters
  controller: App\Controller\ManufacterController::index

manufacter_save:
  path: /admin/manufacters-save/{id}
  controller: App\Controller\ManufacterController::saveManufacter

manufacter_create:
  path: /admin/manufacters-create
  controller: App\Controller\ManufacterController::createManufacter

manufacter_delete:
  path: /admin/manufacters-delete/{id}
  controller: App\Controller\ManufacterController::deleteManufacter
#------------------------------Condition_product------------------------------------
condition_product_list:
  path: /admin/condition-product
  controller: App\Controller\ConditionProductController::index

condition_product_save:
  path: /admin/condition-product-save/{id}
  controller: App\Controller\ConditionProductController::saveConditionProduct

condition_product_create:
  path: /admin/condition-product-create
  controller: App\Controller\ConditionProductController::createConditionProduct

condition_product_delete:
  path: /admin/condition-product-delete/{id}
  controller: App\Controller\ConditionProductController::deleteConditionProduct

#------------------------------Settings------------------------------------
setting:
  path: /admin/setting
  controller: App\Controller\Setting\SettingController::index
#------------------------------Import------------------------------------
import:
  path: /admin/import
  controller: App\Controller\ImportController::index

import_file:
  path: /admin/import-file
  controller: App\Controller\ImportController::importDataFromFile


#------------------------------------------------------------------------
#------------------------------API---------------------------------------
#------------------------------------------------------------------------


#------------------------------AUTH------------------------------------
api_login_check:
  path: /api/login_check

api_register:
  path: /api/register
  controller: App\Controller\Api\RegisterController::index

#------------------------------Products------------------------------------
api_get_products:
  path: /api/all-products
  controller: App\Controller\Api\ApiProductController::allProduct

api_get_product:
  path: /api/product/{id}
  controller: App\Controller\Api\ApiProductController::productById

api_get_products_by_ids:
  path: /api/products
  controller: App\Controller\Api\ApiProductController::productsByIds

  #------------------------------ORDER------------------------------------
api_create_order:
  path: /api/create-order
  controller: App\Controller\Api\ApiOrderController::createOrderFromCart

default:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin
    permanent: true


