controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /
    controller: App\Controller\DashboardController::index

products_list:
    path: /products
    controller: App\Controller\ProductsController::index

categories_list:
     path: /categories
     controller: App\Controller\CategoriesController::index

product_edit:
  path: /product-edit/{id}
  controller: App\Controller\ProductEditController::index
