controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /admin
    controller: App\Controller\DashboardController::index

products_list:
    path: /admin/products
    controller: App\Controller\ProductsController::index

categories_list:
     path: /admin/categories
     controller: App\Controller\CategoriesController::index

categories_Create:
  path: /admin/categories-create
  controller: App\Controller\CategoriesController::createCategory

category_edit:
  path: /admin/category-edit/{id}
  controller: App\Controller\CategoriesController::editCategory


product_edit:
  path: /admin/product-edit/{id}
  controller: App\Controller\ProductEditController::index

product_variation_edit:
  path: /admin/product-variation-edit/{id}
  controller: App\Controller\ProductVariationEditController::index

default:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin
    permanent: true

app_login:
  path: /login
  controller: App\Controller\Auth\LoginController::index

app_logout:
  path: /logout
  controller: App\Controller\Auth\LogoutController::logout


